import React, { useState, useEffect, useRef } from "react";
import axios from "axios";

const ItemData = {
  count: 50100,
  results: [
    {
      listing_id: 817200715,
      state: "active",
      user_id: 44198303,
      category_id: null,
      title:
        "NAG CHAMPA Natural Perfume Roll On with Patchouli, Sandalwood, Champaca Essential Oils, All Natural, Alcohol Free .33 oz.",
      description:
        "Nag Champa Natural Perfume Oil is made with natural ingredients, so it will have a different scent than the synthetic fragrance oils. It is a blend of essential oils including Patchouli and Sandalwood with floral notes of champaca absolute, lavender and geranium, blended with natural plant based fragrances.\n\nA unique scent that blends beautifully with each person’s own body chemistry. \n\nThis is a stronger scented perfume oil so it should take just a little, depending on how strong you like it.\n\nCreated using all natural ingredients, without any of those nasty chemicals in commercial perfumes.  \n\n❀ Alcohol Free\n❀ Preservative Free\n❀ No artificial or synthetic ingredients.\n\nTo Apply: Gently shake and simply apply to wrists, behind ears, nape of neck, or wherever you normally apply perfumes, and gently massage in.  \n\nTips to make Natural Perfumes last longer:\n* Apply to moisturized skin (dry skin doesn&#39;t hold natural fragrances as well).\n* Don&#39;t rub Natural Perfume oil into wrists, gently tap wrists together instead.\n\nLong lasting fragrance, but everyone’s body is different, apply as needed.\n\nComes in a 10 ml. (.33 oz.) Roller bottle with black lid.\n\n*Lid will be taped to prevent leaking during shipping.",
      creation_tsz: 1616727653,
      ending_tsz: 1627268453,
      original_creation_tsz: 1590860583,
      last_modified_tsz: 1616727653,
      price: "10.95",
      currency_code: "USD",
      quantity: 22,
      sku: [],
      tags: [
        "essential oils",
        "essential perfume",
        "roll on perfume",
        "natural perfume",
        "perfume oil",
        "oil perfume",
        "coconut oil",
        "natural fragrance",
        "patchouli perfume",
        "hippie perfume oil",
        "nag champa perfume",
        "nag champa",
        "sandalwood",
      ],
      materials: [
        "fractionated coconut oil",
        "glass roller bottle",
        "Natural Fragrance",
        "Patchouli Oil",
        "Sandalwood Oil",
        "Champaca Oil",
        "Neroli Oil",
        "Lavender Oil",
        "Geranium Oil",
      ],
      shop_section_id: 18108983,
      featured_rank: null,
      state_tsz: 1615342433,
      url:
        "https://www.etsy.com/listing/817200715/nag-champa-natural-perfume-roll-on-with?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 172,
      num_favorers: 31,
      shipping_template_id: 75664585599,
      processing_min: 1,
      processing_max: 3,
      who_made: "i_did",
      is_supply: "false",
      when_made: "2010_2019",
      item_weight: "5",
      item_weight_unit: "oz",
      item_length: "3",
      item_width: "1",
      item_height: "1",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: true,
      is_customizable: true,
      is_digital: false,
      file_data: "",
      should_auto_renew: false,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 216,
      taxonomy_path: ["Bath & Beauty", "Fragrances"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 969232092,
      state: "active",
      user_id: 139098720,
      category_id: null,
      title: "custom crystal box!",
      description:
        "this is a custom crystal box, for beginners or anyone looking to get a crystal box custom to you and your energy.",
      creation_tsz: 1616727652,
      ending_tsz: 1627268452,
      original_creation_tsz: 1616037093,
      last_modified_tsz: 1616727652,
      price: "31.00",
      currency_code: "USD",
      quantity: 14,
      sku: [],
      tags: ["crystal", "custom", "jewelry", "surprise"],
      materials: ["Silver", "Stainless steel"],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1616645616,
      url:
        "https://www.etsy.com/listing/969232092/custom-crystal-box?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 100,
      num_favorers: 1,
      shipping_template_id: null,
      processing_min: 1,
      processing_max: 2,
      who_made: "i_did",
      is_supply: "true",
      when_made: "made_to_order",
      item_weight: "16",
      item_weight_unit: "oz",
      item_length: "14",
      item_width: "7",
      item_height: "0.7",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 1236,
      taxonomy_path: ["Jewelry", "Rings", "Multi-Stone Rings"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 801400634,
      state: "active",
      user_id: 200467553,
      category_id: null,
      title:
        "5 Pack 100% Organic Cotton Reusable Face Mask Made In The USA Facemask FitsTeens Adults Black White Red Gray Navy Blue Unisex Facemasks",
      description:
        "5 Pack of High quality 100% Organic Cotton reusable face mask.  The tie dye are a blend of our cotton, and spandex.  So we can print on them.  Machine washable.  Made In The USA, right here Louisville, Kentucky.  These masks are lightweight and very durable.  They fit teens and adults comfortably.  We have kids size available, for ages 5-12,just click on our store.   Arrives in 2-3 business days.",
      creation_tsz: 1616727650,
      ending_tsz: 1627268450,
      original_creation_tsz: 1590530776,
      last_modified_tsz: 1616727650,
      price: "11.99",
      currency_code: "USD",
      quantity: 4351,
      sku: [
        "5 Pack White ADULT",
        "5 Pack Tie Dye  (Cotton Blend)",
        "5 Pack Black ADULT",
        "5 Pack Mavy Blue ADULT",
        "5 Pack Dark Gray ADULT",
      ],
      tags: [
        "Masks",
        "Face Masks",
        "Facemasks",
        "facemask",
        "reusable",
        "washable",
        "adult",
        "cotton",
        "multi pack",
        "black masks",
        "White",
        "Colors",
        "Gray",
      ],
      materials: ["Organic Cotton"],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1616077922,
      url:
        "https://www.etsy.com/listing/801400634/5-pack-100-organic-cotton-reusable-face?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 10486,
      num_favorers: 206,
      shipping_template_id: 68367699887,
      processing_min: 1,
      processing_max: 1,
      who_made: "i_did",
      is_supply: "false",
      when_made: "2020_2021",
      item_weight: "3",
      item_weight_unit: "oz",
      item_length: "6",
      item_width: "4",
      item_height: "2",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: true,
      taxonomy_id: 1768,
      taxonomy_path: [
        "Accessories",
        "Costume Accessories",
        "Masks & Prosthetics",
        "Masks",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 854067668,
      state: "active",
      user_id: 8135787,
      category_id: null,
      title:
        "Mickey Necklace, Mickey Pumpkin Necklace, Disney jewelry, Disney Halloween, Fall Jewelry, Halloween Jewelry, Pumpkin Necklace, Jack OLantern",
      description:
        "Adorable necklace featuring Mickey Jack O&#39;lantern inspired charm\n\nSize of charm: 1 x 3/4 inch (2.4 x 2 cm) in diameter\n\nChain Length:  Choose from 16 inches,  16 inches with 2 inch extender and 18 inches with 2 inch extender\n\nNecklace fastens with a lobster clasp\n\nAll findings gold plated.\n\n*** CHOKING HAZARD. CLOSE SUPERVISION REQUIRED WHEN CHILDREN ARE WEARING THIS NECKLACE.\n\nComes in a gift box, ready for gift giving.\n\nFor domestic (U.S.) customers:\nShips via USPS First Class mail with delivery confirmation after the payment has been received and the production is complete. You will receive a notice with the tracking number once the item ships..\n\nInternational customers:\nYour items will ship via US First Class mail, but will NOT come with the delivery confirmation number. You will receive the customs form number, which will give you some information about your shipment. If you would like your item to be shipped via priority, registered mail, or with insurance, which enables you to track your shipment, please convo me before purchasing the item. I will give you the quote for the additional cost incurred.\n\nFor more Jewelry Designs from Treasured Adornment, click on\nhttp://www.treasuredadornment.etsy.com\n\nFind Treasured Adornment on FACEBOOK, check out the latest designs, news, &quot;LIKE&quot;, and get discount COUPON CODES!\n\nhttp://www.facebook.com/TreasuredAdornment\n\nThank you for looking!",
      creation_tsz: 1616727650,
      ending_tsz: 1627268450,
      original_creation_tsz: 1599626556,
      last_modified_tsz: 1616727650,
      price: "18.50",
      currency_code: "USD",
      quantity: 3,
      sku: [],
      tags: [
        "Mickey Mouse",
        "Disneyland",
        "Disney Mania",
        "Halloween Party",
        "Disney jewelry",
        "Disney necklace",
        "Pumpkin Necklace",
        "Mickey Necklace",
        "Disney pumpkin",
        "Mickey Pumpkin",
        "Disney outfit",
        "Halloween Necklace",
        "Autumn jewelry",
      ],
      materials: [
        "ballpins",
        "jumprings",
        "chain",
        "spring ring",
        "resin flower",
      ],
      shop_section_id: 6449935,
      featured_rank: null,
      state_tsz: 1599626810,
      url:
        "https://www.etsy.com/listing/854067668/mickey-necklace-mickey-pumpkin-necklace?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 47,
      num_favorers: 11,
      shipping_template_id: 21257437969,
      processing_min: 1,
      processing_max: 5,
      who_made: "i_did",
      is_supply: "false",
      when_made: "2020_2021",
      item_weight: "3",
      item_weight_unit: "oz",
      item_length: "9.5",
      item_width: "8",
      item_height: "1",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: true,
      taxonomy_id: 1217,
      taxonomy_path: ["Jewelry", "Necklaces"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 897534562,
      state: "active",
      user_id: 29902508,
      category_id: null,
      title: "Green Crackle  - Spiral Notebook - Ruled Line",
      description:
        "Plan your life in style. These notebooks are perfect for journaling, school notes, shopping lists and daily tasks. This 118 page spiral notebook with ruled line paper is a perfect companion for everyday use. \n\nDimensions: 6” W x 8” L x .6” H\n\nBeautiful full color image made with my original illustrated designs. Keep yourself organized, by using the personalized header box to add your own handwritten name or notebook title. \n\n.: Front cover printing\n.: 118 ruled line single pages\n.: Black back cover\n\n**Order Fulfillment & Shipping**\nItems are designed exclusively by me and printed & shipped in 1 to 7 business days from Printify Fulfillment Centers USA. You will receive a notification email when items are shipped. If you ordered a digital product, it will be available for instant download, once payment is received. \n\n**Copyright**\nAll design images, including company logo are the property of Daintydoodler Art & Design. No part of these images may be copied, duplicated, or sold. Notebooks are for personal use only.  \n\n If you are interested in licensing my designs or having a custom design made, please contact me.\n\nThank you,\nMelody\n@daintydoodler",
      creation_tsz: 1616727648,
      ending_tsz: 1627268448,
      original_creation_tsz: 1606276350,
      last_modified_tsz: 1616727648,
      price: "12.53",
      currency_code: "USD",
      quantity: 999,
      sku: [],
      tags: [
        "Notebook",
        "Journal",
        "Bible journaling",
        "Daily task list",
        "Shopping list",
        "Music book",
        "Poems",
        "Lyrics",
        "Retro print",
        "School",
        "Composition",
      ],
      materials: ["Digital Illustration"],
      shop_section_id: 31412552,
      featured_rank: null,
      state_tsz: 1606276361,
      url:
        "https://www.etsy.com/listing/897534562/green-crackle-spiral-notebook-ruled-line?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 7,
      num_favorers: 0,
      shipping_template_id: 119266522955,
      processing_min: 1,
      processing_max: 7,
      who_made: "someone_else",
      is_supply: "false",
      when_made: "made_to_order",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: true,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 326,
      taxonomy_path: [
        "Books, Movies & Music",
        "Books",
        "Blank Books",
        "Journals & Notebooks",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 927685548,
      state: "active",
      user_id: 202335842,
      category_id: null,
      title: "Baseball ball pattern A4",
      description:
        "Pattern for DIY crafting the baseball ball. Best for leather craft beginners.",
      creation_tsz: 1616727648,
      ending_tsz: 1627268448,
      original_creation_tsz: 1610544130,
      last_modified_tsz: 1616727648,
      price: "1.00",
      currency_code: "GBP",
      quantity: 99,
      sku: [],
      tags: ["baseball", "ball", "leather"],
      materials: [],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1610544131,
      url:
        "https://www.etsy.com/listing/927685548/baseball-ball-pattern-a4?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 15,
      num_favorers: 0,
      shipping_template_id: null,
      processing_min: null,
      processing_max: null,
      who_made: "i_did",
      is_supply: "true",
      when_made: "2020_2021",
      item_weight: null,
      item_weight_unit: "g",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "mm",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: true,
      file_data: "1 PDF",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 6343,
      taxonomy_path: [
        "Craft Supplies & Tools",
        "Patterns & How To",
        "Patterns & Blueprints",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 911465167,
      state: "active",
      user_id: 290328389,
      category_id: null,
      title: "The Patchwork Face Mask",
      description:
        "100% Cotton \nMade in Los Angeles\nHand Wash Warm\nHang Dry\n\nDimensions Width 6&quot; x Length 11&quot;",
      creation_tsz: 1616727648,
      ending_tsz: 1627268448,
      original_creation_tsz: 1606276517,
      last_modified_tsz: 1616727648,
      price: "18.00",
      currency_code: "USD",
      quantity: 3,
      sku: [],
      tags: ["Face mask", "patchwork"],
      materials: [],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1606277574,
      url:
        "https://www.etsy.com/listing/911465167/the-patchwork-face-mask?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 15,
      num_favorers: 0,
      shipping_template_id: 117694898383,
      processing_min: 3,
      processing_max: 5,
      who_made: "i_did",
      is_supply: "false",
      when_made: "2020_2021",
      item_weight: "1",
      item_weight_unit: "oz",
      item_length: "9",
      item_width: "7",
      item_height: "1",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 12112,
      taxonomy_path: [
        "Bath & Beauty",
        "Personal Care",
        "Face Masks & Coverings",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 775020958,
      state: "active",
      user_id: 280015484,
      category_id: null,
      title:
        "Mountain Snow, Nature Photo, Nevada Wall Art Print, Mt Charleston",
      description:
        "Spring snowfall on Mt Charleston just outside of Las Vegas.  Escape the city in a matter of minutes to venture in a winter wonderland.\nFine art print on acid-free archival matte paper for accurate color and high contrast and high-resolution output.\n\nThickness: 9.5 mil\nWeight: 230 g/m2\nPrinter: Canon iPF8400\nInks: Canon Lucia Inks\n\nTitle: Spring Snow Fall 3\nMedium: Fine art print unframed\nPrint sizes: 8X10, 11X14, 16X20, 20X24\nOrientation: Horizontal\nPlease note that the colors you see on your monitor may differ slightly from those of the print.\nCopyright Duane Pickard. Artwork may not be reproduced or resold without the express permission of the artist.",
      creation_tsz: 1616727648,
      ending_tsz: 1627268448,
      original_creation_tsz: 1584925936,
      last_modified_tsz: 1616727648,
      price: "22.00",
      currency_code: "USD",
      quantity: 1,
      sku: [],
      tags: [
        "photo print",
        "home decor",
        "house warming gift",
        "mount Charleston",
        "out doors",
        "color photo",
        "fine art",
        "wall art",
        "nature",
        "snow",
        "trees",
        "Nevada",
        "Mountain",
      ],
      materials: ["photo paper"],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1584925936,
      url:
        "https://www.etsy.com/listing/775020958/mountain-snow-nature-photo-nevada-wall?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 20,
      num_favorers: 0,
      shipping_template_id: 88704771051,
      processing_min: 5,
      processing_max: 10,
      who_made: "i_did",
      is_supply: "false",
      when_made: "2020_2021",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: true,
      taxonomy_id: 2078,
      taxonomy_path: ["Art & Collectibles", "Prints", "Digital Prints"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 685022167,
      state: "active",
      user_id: 5900768,
      category_id: null,
      title:
        "20 qty 1/4&quot; RING 14G Aluminum Stamping Blanks Flat *Choose Length & End Style* Polished Tumbled Smooth 2&quot; 2 1/4&quot; 2 1/2&quot; 2 3/4&quot; 3&quot; Wrap",
      description:
        "This listing is for *20* 1/4&quot; width Flat RING rectangle stamping blanks cut from 14G aluminum. Choose your size: S (2&quot;) M (2 1/4&quot;) L (2 1/2&quot;) XL (2 3/4&quot;) or wrap styles in 3&quot;, 3 1/4&quot;, 3 1/2&quot; lengths. 3 different end styles available: flat, rounded, or sanded.  RING BLANKS ARE SHIPPED FLAT. YOU WILL NEED A BENDING TOOL TO BEND THESE BLANKS INTO A RING SHAPE. If you don&#39;t see what you&#39;re looking for, please send us a convo and we&#39;ll do our best to accommodate you.\n\nAPPROXIMATE SIZING\n2&quot; Small:\n4 1/2- 6 for 18G               \n4- 5 1/2 for 16G/14G\n\n2 1/4&quot; Medium: \n6 1/2 - 9 for 18G\n6- 8 for 16G/14G\n\n2 1/2&quot; Large: \n9 1/2- 10 1/2 for 18G                      \n8 1/2- 10 for 16G/14G\n\n\n2 3/4&quot; X Large: \n11- 13 for 18G                         \n10 1/2- 12 for 16G/14G\n\n3&quot; Wrap: \n5 1/2 -7 for 18G               \n5- 6 1/2 for 16G/14G\n\n3 1/4&quot; Wrap: \n7- 9 for 18G                     \n6.5- 8.5 for 16G/14G\n\n3 1/2&quot; Wrap: \n10- 12 for 18G                     \n9 1/2- 11 1/2 for 16G/14G\n\nAll our blanks are hand punched, trimmed, deburred, and tumbled to provide you with the highest quality blanks possible. They&#39;re clean, shiny, and free of sharp edges. No more sanding sharp edges or cleaning dirty blanks! Ready for you to finish by adding your own personal touches. \n\nWe&#39;re adding new shapes regularly and will list our newest shapes in our shop announcement. Please be sure to heart our shop and check back often to see our newest creations!\n\n\n***ALL STAMPING BLANKS ARE HANDMADE TO ORDER. CURRENT TURNAROUND TIME IS LISTED IN OUR SHOP ANNOUNCEMENT***",
      creation_tsz: 1616727647,
      ending_tsz: 1627268447,
      original_creation_tsz: 1550770671,
      last_modified_tsz: 1616727647,
      price: "18.50",
      currency_code: "USD",
      quantity: 897,
      sku: [],
      tags: [
        "stamping blanks",
        "jewelry making",
        "aluminum blanks",
        "aluminum rectangle",
        "rectangle blanks",
        "ring blanks",
        "flat ring",
        "ring",
        "bracelet",
        "aluminum cuff",
        "Adjustable ring",
        "Stamping",
        "Aluminum Ring",
      ],
      materials: ["Aluminum"],
      shop_section_id: 22943236,
      featured_rank: 3,
      state_tsz: 1612275271,
      url:
        "https://www.etsy.com/listing/685022167/20-qty-14-ring-14g-aluminum-stamping?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 359,
      num_favorers: 47,
      shipping_template_id: 6683979,
      processing_min: 1,
      processing_max: 5,
      who_made: "i_did",
      is_supply: "true",
      when_made: "made_to_order",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: true,
      is_customizable: true,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: true,
      taxonomy_id: 6220,
      taxonomy_path: ["Craft Supplies & Tools", "Findings"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 977274343,
      state: "active",
      user_id: 64642389,
      category_id: null,
      title: "Fish Net Tied (With Cut Shell)  (EA)",
      description:
        "APPROX.  5  X 10 FEET..... (COMES IN BLUE OR BROWN COLORS).....  RECEIVE (1) NET PER NUMBER ORDERED.",
      creation_tsz: 1616727646,
      ending_tsz: 1627268446,
      original_creation_tsz: 1615260648,
      last_modified_tsz: 1616727646,
      price: "9.95",
      currency_code: "USD",
      quantity: 198,
      sku: ["PIC6382"],
      tags: ["fish nets"],
      materials: [],
      shop_section_id: 19365049,
      featured_rank: null,
      state_tsz: 1615260648,
      url:
        "https://www.etsy.com/listing/977274343/fish-net-tied-with-cut-shell-ea?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 13,
      num_favorers: 3,
      shipping_template_id: 44845450434,
      processing_min: 3,
      processing_max: 5,
      who_made: "someone_else",
      is_supply: "true",
      when_made: "2010_2019",
      item_weight: "21",
      item_weight_unit: "oz",
      item_length: "8",
      item_width: "6",
      item_height: "2",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 1029,
      taxonomy_path: [
        "Home & Living",
        "Home Décor",
        "Wall Décor",
        "Wall Hangings",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 755433905,
      state: "active",
      user_id: 252825989,
      category_id: null,
      title:
        "No gift wrap card INSTANT DOWNLOAD Editable, PDF Printable, Affordable Invite, Insert, Sprinkle, Brunch, gender neutral, simple Baby Shower",
      description:
        "************************************************************\nTRY before you BUY - follow the below link:\nhttps://templett.com/design/demo/asterandrose/3071688\n************************************************************\n\nThis download includes fully editable:\n\nNo Gift Wrap Please card (5x3.5&quot;)\n\n\n************************************************************\n\nYou can change:\n-- All content\n-- Font Colour\n-- Font Style\n-- Font Size\n-- Background Colour\n\nChangable but you will need to message me to change:\n-- Sizes\n\n************************************************************\n\n**Please note this is a digital product - nothing physical will be shipped to you. Once you have placed your order you will receive a link to edit your template online using the software Templett. No waiting for designers - get access immediately!**\n\n\n[id:3071688]",
      creation_tsz: 1616727645,
      ending_tsz: 1627268445,
      original_creation_tsz: 1574393303,
      last_modified_tsz: 1616727645,
      price: "4.27",
      currency_code: "USD",
      quantity: 999,
      sku: [],
      tags: [
        "Editable Template",
        "PDF Printable",
        "Instant Download",
        "baby shower",
        "baby shower invite",
        "baby sprinkle",
        "baby brunch",
        "gender neutral",
        "marble",
        "rose gold",
        "no gift wrap card",
        "no wrapping paper",
        "insert",
      ],
      materials: [],
      shop_section_id: 27528312,
      featured_rank: null,
      state_tsz: 1595558444,
      url:
        "https://www.etsy.com/listing/755433905/no-gift-wrap-card-instant-download?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 178,
      num_favorers: 92,
      shipping_template_id: null,
      processing_min: null,
      processing_max: null,
      who_made: "i_did",
      is_supply: "false",
      when_made: "made_to_order",
      item_weight: null,
      item_weight_unit: "g",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "mm",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: true,
      file_data: "1 PDF",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 1292,
      taxonomy_path: [
        "Paper & Party Supplies",
        "Paper",
        "Invitations & Announcements",
        "Invitations",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 761157191,
      state: "active",
      user_id: 139456731,
      category_id: null,
      title:
        "Fa La Math Shirt Eight Power | Funny Math Nerd Xmas Cute Math Teacher Christmas Tee Plus Deep V-Neck, Tank Top, Hoodie, Raglan, Men, Women",
      description:
        "INDIVIDUAL PRODUCT FEATURES AND MATERIALS\n*Please see product photos for sizing guides\n \nUNISEX TEE SHIRT\n  &gt; 100% soft combed and ring-spun cotton\n  &gt; Fabric weight: 4.2 oz/y² (142 g/m²)\n  &gt; Tear-away label\n  &gt; Shoulder-to-shoulder taping\n  &gt; Side-seamed\n  &gt; Runs true to size\n \nUNISEX V-NECK TEE SHIRT\n  &gt; Made of 100% combed and ringspun cotton\n  &gt; Unisex fit\n  &gt; Side seams\n  &gt; Coverstitched v-neck and hemmed sleeves\n  &gt; Shoulder-to-shoulder taping\n  &gt; Runs true to size\n \nWOMEN’S DEEP V-NECK TEE SHIRT\n  &gt; Slim fit\n  &gt; 100% Soft cotton (fiber content may vary for different colors)\n  &gt; Light fabric (4.2 oz/yd² (142 g/m²))\n  &gt; Sewn in label\n  &gt; Runs smaller than usual\n \nUNISEX TANK TOP\n  &gt; 100% combed and ringspun cotton\n  &gt; Tri-blends are 50% polyester/25% combed/25% ringspun cotton/rayon\n  &gt; Fabric weight: 4.2 oz./yd2 (142.40 g/m²)\n  &gt; 30 singles thread weight\n  &gt; Side-seamed, unisex sizing\n \nWOMEN’S RACERBACK TANK TOP\n  &gt; Slim fit\n  &gt; 50% polyester/25% combed ring-spun cotton/25% rayon\n  &gt; Light Fabric: 4.2 oz (142 g/m2)\n  &gt; Satin label\n  &gt; Raw edge seams\n\nINFANT JERSEY TEE\n  &gt; Classic fit\n  &gt; 100% Cotton (fibre content may vary for different colors)\n  &gt; Light fabric (4.5 oz/yd² (153 g/m²))\n  &gt; Runs true to size\n \nKIDS JERSEY TEE\n  &gt; Classic fit\n  &gt; 100% Flexible cotton (fibre content may vary for different colors)\n  &gt; Light fabric (4.5 oz/yd² (153 g/m²))\n  &gt; Tear away label\n  &gt; Runs true to size\n \nYOUTH TEE SHIRT\n  &gt; Regular fit\n  &gt; 100% Soft cotton (fibre content may vary for different colors)\n  &gt; Light fabric (5.2 oz /yd² (176 g/m²))\n  &gt; Tear away label\n  &gt; Runs smaller than usual\n\n▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\nPROCESSING/SHIPPING TIME:\nAll items are made to order and require 1-5 days (usually closer to 3) to print based on how busy the printing company is.  Processing time increases by a couple of days from Mid-December until around Christmas.\nItems are usually shipped by USPS First Class mail unless a faster option is more affordable.\nShipping is estimated at 1-5 days once the post office has the package. Items are shipped from the closest fulfillment center (Florida, Colorado, North Carolina, Iowa, and Nevada) so the closer you live to one of them, the faster your shipping will be.\nYou will receive a notification from Etsy once your item has been shipped.\n \n▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\nWASH/CARE INSTRUCTIONS:\nThese shirts can all be washed with your regular laundry, but to extend the life of your shirt:\n  &gt; Wash inside out\n  &gt; Tumble dry on low or hang to dry\n  &gt; Do not iron over design\n \n▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\nADDITIONAL QUESTIONS\nI do my best to respond within an hour, unless its bed time or I’m out having an evening cocktail.  Please feel free to message me on the Etsy messaging.  I don’t generally respond to emails sent to my regular email address, so the Etsy messaging is the quickest way to get a hold of me.\n \n▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄\nBE SOCIAL\nBe sure to follow us on Instagram and tag us when you get your order @FacultyLoungers. We’ll keep that account updated with new products and also offer giveaways and news about flash sales just for followers.",
      creation_tsz: 1616727644,
      ending_tsz: 1627268444,
      original_creation_tsz: 1576023519,
      last_modified_tsz: 1616727644,
      price: "25.00",
      currency_code: "USD",
      quantity: 58883,
      sku: [],
      tags: [
        "funny math shirts",
        "fa la la math nerd",
        "xmas math tee",
        "math teacher gift",
        "math major",
        "math professor",
        "ugly sweater",
        "funny christmas tee",
        "nerdy xmas sweater",
        "teacher christmas",
        "fa la 8th power",
        "christmas exponent",
        "boys girls sizes",
      ],
      materials: [
        "cotton",
        "tshirt",
        "shirt",
        "t shirt",
        "tee",
        "tank top",
        "teacher gift",
        "dtg",
        "black t shirt",
        "text",
        "v neck",
        "hoodie",
        "raglan",
      ],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1588765000,
      url:
        "https://www.etsy.com/listing/761157191/fa-la-math-shirt-eight-power-funny-math?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 53,
      num_favorers: 11,
      shipping_template_id: 52170880885,
      processing_min: 2,
      processing_max: 6,
      who_made: "i_did",
      is_supply: "false",
      when_made: "made_to_order",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: true,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: true,
      taxonomy_id: 482,
      taxonomy_path: [
        "Clothing",
        "Unisex Adult Clothing",
        "Tops & Tees",
        "T-shirts",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 562320385,
      state: "active",
      user_id: 64642389,
      category_id: null,
      title: "Large India Ocean Seashell Mix   (Kilo Size Bag)  (EA)",
      description:
        "Approx.    2  to 4 inches.......  Receive a  kilo size bag of shells per number ordered..... (Approx.  2 pounds).\n\nAll mixes can vary slightly from picture.",
      creation_tsz: 1616727644,
      ending_tsz: 1627268444,
      original_creation_tsz: 1507063372,
      last_modified_tsz: 1616727644,
      price: "6.95",
      currency_code: "USD",
      quantity: 25,
      sku: ["SS0321-L"],
      tags: [
        "seashell mixes",
        "bulk seashells",
        "seashell bag mixes",
        "craft seashells",
        "seashell assortment",
      ],
      materials: [],
      shop_section_id: 22433760,
      featured_rank: null,
      state_tsz: 1597244801,
      url:
        "https://www.etsy.com/listing/562320385/large-india-ocean-seashell-mix-kilo-size?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 1061,
      num_favorers: 120,
      shipping_template_id: 44845450434,
      processing_min: 3,
      processing_max: 5,
      who_made: "someone_else",
      is_supply: "true",
      when_made: "2010_2019",
      item_weight: "36",
      item_weight_unit: "oz",
      item_length: "6",
      item_width: "6",
      item_height: "4",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 562,
      taxonomy_path: ["Craft Supplies & Tools"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 988427577,
      state: "active",
      user_id: 177142609,
      category_id: null,
      title: "Custom Boss baby order",
      description:
        "theme: Boss baby \n\nONE letters $55\n24 boxes $40 \n\n\ndate: Need before June 1st \nName: Ivana",
      creation_tsz: 1616727644,
      ending_tsz: 1627268444,
      original_creation_tsz: 1616727644,
      last_modified_tsz: 1616727645,
      price: "95.00",
      currency_code: "USD",
      quantity: 1,
      sku: [],
      tags: [],
      materials: [],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1616727644,
      url:
        "https://www.etsy.com/listing/988427577/custom-boss-baby-order?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 0,
      num_favorers: 0,
      shipping_template_id: 61316404590,
      processing_min: null,
      processing_max: null,
      who_made: "i_did",
      is_supply: "false",
      when_made: "made_to_order",
      item_weight: "16",
      item_weight_unit: "oz",
      item_length: "8",
      item_width: "8",
      item_height: "8",
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 9122,
      taxonomy_path: [
        "Craft Supplies & Tools",
        "Kitchen Supplies",
        "Baking & Cake Decorations",
        "Cake Toppers & Picks",
        "Cake Toppers",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 816971945,
      state: "active",
      user_id: 49805551,
      category_id: null,
      title:
        "1/3/5 Strands Tile Bracelet,Enamel Beaded Macrame Cord Bracelets,Tila Bracelet",
      description:
        "Dear Customers:\nIf you need quantity for any item in our shop please contact us.\nThank you!\n-----------------------------------------------------------------------------------\nMaterial: Enamel Tile Beads,Macrame Cord\n\nQuantity: 1 / 3 / 5 Strands\n\nEnamel Tile Beads Sizes: approx  5mm ( As reference )\n\nBracelet Length: approx 17.5cm-18cm  ( As reference )\n\nColor: as picture color\n-----------------------------------------------------------------------------------",
      creation_tsz: 1616727644,
      ending_tsz: 1627268444,
      original_creation_tsz: 1590808355,
      last_modified_tsz: 1616727644,
      price: "5.99",
      currency_code: "USD",
      quantity: 1,
      sku: ["18erf"],
      tags: [
        "Jewelry Bracelet",
        "Bracelet",
        "Charm Bracelet",
        "Beaded Bracelet",
        "DIY Bracelets",
        "Fashion Bracelet",
        "Tile Bracelet",
        "Tila Bracelet",
        "Enamel Bracelets",
        "Enamel beaded",
        "Cord Bracelets",
      ],
      materials: ["Metal Alloy", "Enamel Tile Beads", "Macrame Cord"],
      shop_section_id: 15675004,
      featured_rank: null,
      state_tsz: 1600153346,
      url:
        "https://www.etsy.com/listing/816971945/135-strands-tile-braceletenamel-beaded?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 754,
      num_favorers: 75,
      shipping_template_id: 71446671918,
      processing_min: 3,
      processing_max: 5,
      who_made: "i_did",
      is_supply: "false",
      when_made: "2020_2021",
      item_weight: null,
      item_weight_unit: "g",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "mm",
      is_private: false,
      recipient: "teens",
      occasion: null,
      style: ["Fashion of Bracelets", "Bracelets of Jewelry Findings"],
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: false,
      language: "en-US",
      has_variations: true,
      taxonomy_id: 1195,
      taxonomy_path: ["Jewelry", "Bracelets", "Beaded Bracelets"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 829818708,
      state: "active",
      user_id: 136357749,
      category_id: null,
      title: "Black Faux Leather Earrings with a Feather",
      description:
        "Black Faux Leather Earrings with a Feather charm.\n\n#blackleather #feather #earrings #charms #fauxleather",
      creation_tsz: 1616727644,
      ending_tsz: 1627268444,
      original_creation_tsz: 1595558996,
      last_modified_tsz: 1616727644,
      price: "6.00",
      currency_code: "USD",
      quantity: 1,
      sku: [],
      tags: [],
      materials: ["Faux leather"],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1595558996,
      url:
        "https://www.etsy.com/listing/829818708/black-faux-leather-earrings-with-a?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 5,
      num_favorers: 0,
      shipping_template_id: 83747160280,
      processing_min: 1,
      processing_max: 3,
      who_made: "i_did",
      is_supply: "false",
      when_made: "2020_2021",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 1208,
      taxonomy_path: ["Jewelry", "Earrings", "Dangle & Drop Earrings"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 843720141,
      state: "active",
      user_id: 260325514,
      category_id: null,
      title: "Funny crime scene t-shirt",
      description: "Design can be put on tank or tee. Color can be customized.",
      creation_tsz: 1616727643,
      ending_tsz: 1627268443,
      original_creation_tsz: 1595558681,
      last_modified_tsz: 1616727643,
      price: "18.00",
      currency_code: "USD",
      quantity: 10,
      sku: [],
      tags: ["diy shirts", "crime scene shirt", "funny shirt"],
      materials: [],
      shop_section_id: null,
      featured_rank: null,
      state_tsz: 1595558681,
      url:
        "https://www.etsy.com/listing/843720141/funny-crime-scene-t-shirt?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 59,
      num_favorers: 1,
      shipping_template_id: 96225485280,
      processing_min: 3,
      processing_max: 5,
      who_made: "i_did",
      is_supply: "false",
      when_made: "made_to_order",
      item_weight: null,
      item_weight_unit: null,
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: null,
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: true,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 11115,
      taxonomy_path: [
        "Clothing",
        "Women's Clothing",
        "Tops & Tees",
        "T-shirts",
        "Graphic Tees",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 639611037,
      state: "active",
      user_id: 154868190,
      category_id: null,
      title: "Kathleen Digital Resume & Sorority Recruitment Packet",
      description:
        "Are you Ready for Recruitment? Is your resume creative, concise and complete with all the information sorority alumnae need to write letters of recommendation? Our Digital Resumes and Sorority Recruitment Packets are designed with Rush in mind. All items are DIGITAL and customization and electronic delivery is usually complete in 24 hours or less. Resume and cover documents are usually delivered in 2 hours or less. Items are listed as &quot;physical&quot; to allow customers to choose from multiple color options. \n\nComprehensive How to Guide included with every purchase. Resume and Cover Letter templates are delivered in document format (Word or Pages). Ready for Recruitment provides ready to print PDF card and label documents.  Cards are designed to print on white card stock, and labels are designed for Avery 5160 and 5163 labels. We can format for any Avery compatible card or label product and honor all special requests without additional charge.\n\nPackets were designed with DIY printers in mind. No printer? No problem.  We can PRINT and ASSEMBLE all or part of your Packet! We customize our options to suit your needs and budget. We have coordinating pocket folders, file folders and envelopes. No minimum quantity. Let us help you put together a stylish and affordable packet.  \n\nRESUME & COVER includes:\n2. Two Resume Templates (1 with embedded photo) - Word or Pages format\n3. Two Cover Letter Templates (customize or one size fits all)- Word or Pages format\n4. Two Letterhead Options (1 with embedded photo) and Letterhead for additional pages - Word or Pages Format\n\nLABEL SET includes:\n1. Home Address Label - Ready to print PDF formatted for 1 x 2.63 inch and 2 x 4 inch labels (compatible with Avery 5160 and 5163 labels)\n2. Folder Label - Ready to print PDF formatted for 2 x 4 inch labels (compatible with Avery 5163 labels)\n3. Photo Label - Ready to pint PDF formatted for 1 x 2.63 inch labels (compatible with Avery 5160 labels) \n\nCARD SET includes:\n1. Business Card (2 Style Options) - Ready to print PDF designed to be printed on card stock and then cut from page\n2. Postcard (2 Style Options) - Ready to print PDF designed to be printed on card stock and then cut from the page\n\nCoordinating Thank You Note and Notecard Collections sold separately. Find them here: https://etsy.me/2XkdY4f\n\nPACKET includes ALL ITEMS listed above.\n\nSORORITY ADDRESS LABELS (Not included in PACKET or LABEL SET)\nOrder a set of Sorority Address Labels to complete your look.  I will create files for all of the Active Chapters participating in Formal Recruitment. Labels can be formatted to suit your individual needs: 2 Chi Omega, 2 Kappa Kappa Gamma, 1 Delta Zeta etc…\n\nResume, Card, and Label PNG Files are available on request.\n\nWatercolor graphics by the talented Catherine Haugland. See more of Catherine&#39;s amazing work here: https://creativemarket.com/avalonrosedesign.\n\nA special thanks to the beautiful Lynsey Ruiz for allowing me to showcase her photo. Photography credit to @jaymarroquin.",
      creation_tsz: 1616727642,
      ending_tsz: 1627268442,
      original_creation_tsz: 1535414447,
      last_modified_tsz: 1616727642,
      price: "8.00",
      currency_code: "USD",
      quantity: 43,
      sku: [],
      tags: [
        "Social Resume",
        "Sorority Resume",
        "Sorority Packet",
        "Recruitment Packet",
        "Rush Resume",
        "Rush Packet",
        "Resume Template",
        "Address Labels",
        "Thank You Notes",
        "Business Cards",
        "Letterhead",
        "Digital Templates",
        "Digital Download",
      ],
      materials: [],
      shop_section_id: 29381287,
      featured_rank: null,
      state_tsz: 1597855547,
      url:
        "https://www.etsy.com/listing/639611037/kathleen-digital-resume-sorority?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 1278,
      num_favorers: 53,
      shipping_template_id: null,
      processing_min: 1,
      processing_max: 1,
      who_made: "collective",
      is_supply: "false",
      when_made: "2020_2021",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: true,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: true,
      taxonomy_id: 1876,
      taxonomy_path: [
        "Paper & Party Supplies",
        "Paper",
        "Stationery",
        "Design & Templates",
        "Templates",
        "Résumé Templates",
      ],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 712007459,
      state: "active",
      user_id: 24162593,
      category_id: null,
      title:
        "Wedding Seating Chart INSTANT DOWNLOAD Minimalist Black and White Basic Wedding Seating Plan Editable Template Printable Templett W034",
      description:
        "This listing contains a Digitally Editable high-resolution Printable template for a Minimalist Black and White Basic wedding seating chart. This template is INSTANTLY available to you after purchasing and you can quickly and easily edit it online within your browser. You can then save, download and print right away!\n \n-------------------------------------\nDEMO - Try before you buy\n-------------------------------------\n↠ Copy and paste this link in your browser to test out the template:\nhttps://templett.com/design/demo/StandishDesignStudio/1706547\n \n--------------------------\nWHAT’S INCLUDED?\n--------------------------\n↠ Wedding Seating Chart - 24&quot; x 18&quot;\n\n--------------------------\nMATCHING ITEMS\n--------------------------\n↠ www.etsy.com/shop/StandishDesignStudio?ref=seller-platform-mcnav&search_query=W034\n\n--------------------------\nWHAT’S EDITABLE?\n--------------------------\n↠ All text can be changed, moved around, the new text box can be added\n↠ All fonts can be edited - font style, size, color\n↠ You can change color/texture of the background\n↠ Resize and move graphics around\n↠ You can add your own photos\n\n↠ Colors of watercolor elements CANNOT be changed\n \n--------------------\nINSTRUCTIONS\n--------------------\nA basic step-by-step guide is included with your purchase. Please download that and then check your email for a direct link to the templates sent by TEMPLETT.\n \nYou can then begin editing the template within your browser! :)\n \nThe Templett web application was designed specifically for editing templates so it is very easy to use! You can save your files and come back to the web app at any time and continue editing your wedding template. It will always be available to you.\n* These templates are only editable within your web browser on a computer. They do not work on mobile devices!\n \nIf you aren’t comfortable using the online software, I can put it together for you!\nPlease just purchase this additional listing ALONG with the original template listing:\nwww.etsy.com/listing/633161353/need-help-putting-together-your-templett\n \n------------------\nPLEASE NOTE\n------------------\n \nThis is a listing for an editable template. No physical item will be shipped.\nDue to the nature of this product, digital downloads are not eligible for refunds.\n \nThis file is for personal use only. You may not share, forward, sell or re-distribute the file. It is for non-commercial use only.\n \nCopyright © 2016 Standish Design Studio\n \n---------------------------------------------------------------------\n \nFeel free to visit my shop for more products!\nwww.etsy.com/shop/StandishDesignStudio\n \n \nThank you for stopping by • enjoy your day :)\n \n[id:1706547]",
      creation_tsz: 1616727642,
      ending_tsz: 1627268442,
      original_creation_tsz: 1559794358,
      last_modified_tsz: 1616727642,
      price: "16.00",
      currency_code: "USD",
      quantity: 298,
      sku: ["W034"],
      tags: [
        "Template",
        "Printable",
        "Templett",
        "Instant Download",
        "Editable",
        "Wedding",
        "Wedding Set",
        "Seating Chart",
        "Table Plan",
        "Digital File",
        "Black and White",
        "Basic",
        "Minimalistic",
      ],
      materials: [
        "Digital File Only",
        "Templett",
        "Instant Download",
        "Editable",
        "Wedding Signage",
        "Wedding Set",
        "Template Download",
        "Printable",
        "DIY",
        "Template",
        "Seating Chart",
        "Seating Plan",
        "Table Plan",
      ],
      shop_section_id: 24360551,
      featured_rank: null,
      state_tsz: 1574393286,
      url:
        "https://www.etsy.com/listing/712007459/wedding-seating-chart-instant-download?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 190,
      num_favorers: 7,
      shipping_template_id: null,
      processing_min: null,
      processing_max: null,
      who_made: "i_did",
      is_supply: "false",
      when_made: "made_to_order",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: "not_specified",
      occasion: null,
      style: ["Rustic", "Boho"],
      non_taxable: false,
      is_customizable: true,
      is_digital: true,
      file_data: "1 PDF",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 6121,
      taxonomy_path: ["Weddings", "Decorations", "Signs"],
      used_manufacturer: false,
      is_vintage: false,
    },
    {
      listing_id: 722897481,
      state: "active",
      user_id: 31070928,
      category_id: null,
      title: "Vintage Gotcha Boarding Company t-shirt",
      description:
        "Vintage Gotcha Boarding Company t-shirt\nNo size tag. See pics for details\nPit to pit 21&quot;\nSleeve 9&quot;\nLength collar to bottom 25.5&quot;\n\n\n\n#gotcha #boardingcompany #skate #skateboard #vintage #90s",
      creation_tsz: 1616727642,
      ending_tsz: 1627268442,
      original_creation_tsz: 1563675258,
      last_modified_tsz: 1616727642,
      price: "20.00",
      currency_code: "USD",
      quantity: 1,
      sku: [],
      tags: [
        "gotcha",
        "Boarding Company",
        "skate",
        "skateboard",
        "vintage",
        "90s",
      ],
      materials: [],
      shop_section_id: 22895414,
      featured_rank: null,
      state_tsz: 1563675258,
      url:
        "https://www.etsy.com/listing/722897481/vintage-gotcha-boarding-company-t-shirt?utm_source=p2test&utm_medium=api&utm_campaign=api",
      views: 97,
      num_favorers: 2,
      shipping_template_id: 41529263749,
      processing_min: 3,
      processing_max: 5,
      who_made: "someone_else",
      is_supply: "false",
      when_made: "1990s",
      item_weight: null,
      item_weight_unit: "oz",
      item_length: null,
      item_width: null,
      item_height: null,
      item_dimensions_unit: "in",
      is_private: false,
      recipient: null,
      occasion: null,
      style: null,
      non_taxable: false,
      is_customizable: false,
      is_digital: false,
      file_data: "",
      should_auto_renew: true,
      language: "en-US",
      has_variations: false,
      taxonomy_id: 482,
      taxonomy_path: [
        "Clothing",
        "Unisex Adult Clothing",
        "Tops & Tees",
        "T-shirts",
      ],
      used_manufacturer: false,
      is_vintage: true,
    },
  ],
  params: {
    limit: "20",
    offset: 0,
    page: null,
    keywords: null,
    sort_on: "created",
    sort_order: "down",
    min_price: null,
    max_price: null,
    color: null,
    color_accuracy: 0,
    tags: null,
    taxonomy_id: null,
    location: null,
    lat: null,
    lon: null,
    region: null,
    geo_level: "city",
    accepts_gift_cards: "false",
    translate_keywords: "false",
  },
  type: "Listing",
  pagination: {
    effective_limit: 20,
    effective_offset: 0,
    next_offset: 20,
    effective_page: 1,
    next_page: 2,
  },
};

export default ItemData;
